project:
  type: website
  output-dir: "./docs"

website:
  open-graph: true
  title: "Simon Oiry"
  description: "I am a PhD student in Marine Ecology at Nantes University. This is my personal website."
  favicon: img/Website_logo.png
  navbar:
    logo: img/Website_logo.png
    left:
      - href: index.qmd
        text: "**Home**"
      - href: My_PhD.qmd
        text: "**My PhD**" 
      - href: GeneralMap.qmd
        text: "**My Project**"
      - href: Publications.qmd
        text: "**Publications**" 
      - href: about_me.qmd
        text: "**About me**"
      - href: about.qmd
        text: "**About this Website**" 
    right:
      - icon: twitter
        href: https://twitter.com/OirySig
      - icon: github
        href: https://github.com/SigOiry
      - icon: linkedin
        href: https://www.linkedin.com/in/simon-oiry-140289134/
      - icon: search
        href: https://www.researchgate.net/profile/Simon-Oiry  
      - icon: envelope
        href: "mailto:oirysimon@gmail.com"  
      - href: ./index.html
        text: English
      - href: ./fr/index.html
        text: Fran√ßais
format:
  html:
    theme: 
      light: custom_light.scss
      dark: custom_dark.scss
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 3000px
      margin-width: 0px
      gutter-width: 0px

lang: en

editor: visual

