project:
  type: website
  output-dir: "./docs/fr"

website:
  navbar:
    left:
      - href: index.qmd
        text: A propos de moi      
      - href: GeneralMap.qmd
        text: Carte générale
      - about.qmd
    right:
      - href: ../index.html
        text: English
      - href: .index.html
        text: Français

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    grid:
      body-width: 1500px
      margin-width: 0px
      sidebar-width: 0px
      
      

lang: fr

editor: visual

