project:
  type: website
  output-dir: "./docs/fr"

website:
  open-graph: true
  title: "Simon Oiry"
  description: "Marine Ecologist and PhD student"
  favicon: img/Website_logo.png
  navbar:
    logo: img/Website_logo.png
    left:
      - href: index.qmd
        text: "**Accueil**"
      - href: My_PhD.qmd
        text: "**Mon Doctorat**" 
      - href: GeneralMap.qmd
        text: "**Carte de mes Projets**"
      - href: about_me.qmd
        text: "**A propos de moi**"
      - href: about.qmd
        text: "**A propos de ce site web**" 
    right:
      - icon: twitter
        href: https://twitter.com/OirySig
      - icon: github
        href: https://github.com/SigOiry
      - icon: linkedin
        href: https://www.linkedin.com/in/simon-oiry-140289134/
      - icon: search
        href: https://www.researchgate.net/profile/Simon-Oiry  
      - icon: envelope
        href: "mailto:oirysimon@gmail.com"  
      - href: ../index.html
        text: English
      - href: ./index.html
        text: Fran√ßais
format:
  html:
    theme: 
      light: custom_light.scss
      dark: custom_dark.scss
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 3000px
      margin-width: 0px
      gutter-width: 0px
      
      

lang: fr

editor: visual

